# Generated by rust2rpm 24
%bcond_without check

%global crate eza
%global debug_package %{nil}

Name:           rust-eza
Version:        0.10.8
Release:        0%{?dist}
Summary:        Modern replacement for ls

License:        MIT
URL:            https://crates.io/crates/eza
Source:         %{crates_source}

BuildRequires:  rust-packaging >= 23
BuildRequires:  pandoc

%global _description %{expand:
A modern replacement for ls.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# (MIT OR Apache-2.0) AND BSD-3-Clause AND GPL-2.0-only WITH GCC-exception-2.0 AND MIT
# MIT
# MIT OR Apache-2.0
# MIT OR Apache-2.0 OR Zlib
# Unlicense OR MIT
# Zlib OR Apache-2.0 OR MIT
License:        MIT AND (MIT OR Apache-2.0) AND (MIT OR Apache-2.0 OR Zlib) AND (Zlib OR Apache-2.0 OR MIT) AND (Unlicense OR MIT) AND ((MIT OR Apache-2.0) AND BSD-3-Clause AND GPL-2.0-only WITH GCC-exception-2.0 AND MIT)
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENCE
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc CODE_OF_CONDUCT.md
%doc CONTRIBUTING.md
%doc README.md
%doc SECURITY.md
%{_mandir}/man1/eza.1*
%{_mandir}/man5/eza_colors.5*
%{_mandir}/man5/eza_colors-explanation.5*
%{_datadir}/bash-completion/completions/eza
%{_datadir}/fish/vendor_completions.d/eza.fish
%{_datadir}/zsh/site-functions/_eza
%{_bindir}/eza

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
mkdir -p "target/man"
pandoc --standalone -f markdown -t man man/eza.1.md                     > "target/man/eza.1"
pandoc --standalone -f markdown -t man man/eza_colors.5.md              > "target/man/eza_colors.5"
pandoc --standalone -f markdown -t man man/eza_colors-explanation.5.md  > "target/man/eza_colors-explanation.5"

%install
%cargo_install
install -Dpm0644 -t %{buildroot}%{_mandir}/man1 \
    target/man/eza.1
install -Dpm0644 -t %{buildroot}%{_mandir}/man5 \
    target/man/eza_colors.5 \
    target/man/eza_colors-explanation.5
install -Dpm0644 -t %{buildroot}%{_datadir}/bash-completion/completions \
    completions/bash/eza
install -Dpm0644 -t %{buildroot}%{_datadir}/fish/vendor_completions.d \
    completions/fish/eza.fish
install -Dpm0644 -t %{buildroot}%{_datadir}/zsh/site-functions \
    completions/zsh/_eza

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon Aug 14 2023 Eir Wilson <fedora@eirrw.com> 0.10.7-4
- add manfiles and completions (fedora@eirrw.com)

* Mon Aug 14 2023 Eir Wilson <fedora@eirrw.com> 0.10.7-3
- try to fix debug_package failure (fedora@eirrw.com)

* Mon Aug 14 2023 Eir Wilson <fedora@eirrw.com> 0.10.7-2
- use cargo release flag

* Mon Aug 14 2023 Eir Wilson <fedora@eirrw.com> 0.10.7-1
- new package built with tito
