# Generated by rust2rpm 24
%bcond_without check

%global crate timeago

Name:           rust-timeago
Version:        0.3.1
Release:        %autorelease
Summary:        Given a Duration, lossily format it like in 'N days ago'

# Upstream license specification: MIT/Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/timeago
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          timeago-fix-metadata.diff

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Given a Duration, lossily format it like in 'N days ago'. Parsing it
back to Duration is not supported yet.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%doc README.md
%{_bindir}/timeago

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon Aug 14 2023 Eir Wilson <fedora@eirrw.com> 0.3.1-1
- new package built with tito

%autochangelog
